language: python
python:
  - "2.6"
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - python setup.py install
  - pip install coveralls
  - pip install pep8
script:
  - pep8 pyramda
  - python setup.py nosetests
after_success:
  - coveralls
